Energinet-DataHub/geh-settlement-report

source/settlement-report/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/Generators/MeteringPointTimeSeriesFileGenerator.cs
source/settlement-report/CalculationResults/CalculationResults.Infrastructure/SettlementReports_v2/SettlementReportMeteringPointTimeSeriesResultRepository.cs
source/settlement-report/CalculationResults/CalculationResults.IntegrationTests/Infrastructure/SettlementReports_v2/SettlementReportMeteringPointTimeSeriesResultRepositoryTests.cs

skip count for time series

---

.github/workflows/cd.yml
.github/workflows/ci-orchestrator.yml
.github/workflows/detect-changes.yml

conditional deployment settlement report

---

source/settlement-report/Test.Core/Test.Core.csproj

Upgrade usages of TestCommon to 6.1.0

---

source/settlement-report/DatabaseMigration/DatabaseMigration.csproj
source/settlement-report/DatabaseMigration/Scripts/202409121100_Add_FilterProperties_to_SettlementReport.sql
source/settlement-report/Orchestration.SettlementReports.IntegrationTests/Functions/SettlementReports/SettlementReportOrchestrationTests.cs
source/settlement-report/SettlementReports.Application/SettlementReports_v2/GetSettlementReportsHandler.cs
source/settlement-report/SettlementReports.Application/SettlementReports_v2/SettlementReport.cs
source/settlement-report/SettlementReports.Interfaces/SettlementReports_v2/Models/RequestedSettlementReportDto.cs

add filter properties to SettlementReport

---

source/settlement-report/SettlementReports.Application/SettlementReports_v2/GetSettlementReportsHandler.cs

Fixes a problem with old reports where GridAreas wasn't saved.

Fixes a problem with old reports where GridAreas wasn't saved.

---

source/settlement-report/SettlementReports.Infrastructure/Helpers/DatabricksJobsHelper.cs

Params for the python job wasn't correct, this should fix this.

Fix Job Params

---

source/settlement-report/DatabaseMigration/DatabaseMigration.csproj
source/settlement-report/DatabaseMigration/Scripts/202409121100_Increase_GridAreas_Column_Size.sql

increase gridareas column size

---

source/settlement-report/Common.Infrastructure/Common.Infrastructure.csproj
source/settlement-report/SettlementReports.Infrastructure/SettlementReports.Infrastructure.csproj

fix: Upgrade core package/backoff.

---

source/settlement-report/Common.Infrastructure/Telemetry/SubsystemInformation.cs
source/settlement-report/Orchestration.SettlementReports.IntegrationTests/Fixtures/OrchestrationSettlementReportsAppFixture.cs
source/settlement-report/Orchestration.SettlementReports.IntegrationTests/Functions/SettlementReports/SettlementReportOrchestrationTests.cs
source/settlement-report/Orchestration.SettlementReports/Functions/SettlementReports/SettlementReportDownloadTrigger.cs
source/settlement-report/Orchestration.SettlementReports/Functions/SettlementReports/SettlementReportListHttpTrigger.cs
source/settlement-report/Orchestration.SettlementReports/Functions/SettlementReports/SettlementReportRequestTrigger.cs
source/settlement-report/Orchestration.SettlementReports/Orchestration.SettlementReports.csproj
source/settlement-report/Orchestration.SettlementReports/Program.cs
source/settlement-report/SettlementReports.Application/SettlementReports_v2/ISettlementReportJobsFileRepository.cs
source/settlement-report/SettlementReports.Infrastructure/Factories/EnergyResultFactory.cs
source/settlement-report/SettlementReports.Infrastructure/Factories/WholesaleServicesFactory.cs
source/settlement-report/SettlementReports.Infrastructure/SettlementReports.Infrastructure.csproj
source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/SettlementReportChargeLinkPeriodsRepository.cs
source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/SettlementReportChargePriceRepository.cs
source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/SettlementReportWholesaleRepository.cs
source/settlement-report/SettlementReports.Interfaces/CalculationResults/Model/EnergyResults/AggregatedTimeSeries.cs
source/settlement-report/SettlementReports.Interfaces/CalculationResults/Model/EnergyResults/AggregatedTimeSeriesQueryParameters.cs
source/settlement-report/SettlementReports.Interfaces/CalculationResults/Model/EnergyResults/EnergyResult.cs
source/settlement-report/SettlementReports.Interfaces/CalculationResults/Model/WholesaleResults/WholesaleServicesQueryParameters.cs
source/settlement-report/SettlementReports.Interfaces/SettlementReports.Interfaces.csproj
source/settlement-report/SettlementReports.Interfaces/SettlementReports_v2/Models/SettlementReportRequestFilterDto.cs
source/settlement-report/SettlementReports.WebAPI/Controllers/SettlementReportsController.cs
source/settlement-report/SettlementReports.WebAPI/Program.cs
source/settlement-report/SettlementReports.WebAPI/SettlementReports.WebAPI.csproj

Add revision log to both Orchestration version and WebAPI version of Settlement Reports

Add revision log to function and API

---

source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/Generators/MeteringPointMasterDataFileGenerator.cs
source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/SettlementReportMeteringPointMasterDataRepository.cs
source/settlement-report/SettlementReports.IntegrationTests/Application/SettlementReports/SettlementReportFileRequestHandlerIntegrationTests.cs

remove two columns for energy suppliers in MDMP

---

source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountTotalFileGenerator.cs

No SYO on charge owner.

---

source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountFileGenerator.cs
source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountTotalFileGenerator.cs

Also updates error messages for conversion to be more detailed

Add "null" handling for monthly amounts total

---

source/settlement-report/Orchestration.SettlementReports/Functions/SettlementReports/SettlementReportListHttpTrigger.cs
source/settlement-report/SettlementReports.Infrastructure/Experimental/DatabricksSqlQueryExecutor.cs
source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/Generators/MonthlyAmountTotalFileGenerator.cs

also remove parallel download.

Only get status for running reports

---

source/settlement-report/SettlementReports.Application/Handlers/DatabricksJobNames.cs
source/settlement-report/SettlementReports.Infrastructure/Helpers/DatabricksJobsHelper.cs

There is now two jobs, one for balancefixing and one for the other, this PR updates the names, and also changes the names of a parameter depending on which jobs is used.

Update to actual names for jobs, and add new param for blancefixing

---

source/settlement-report/SettlementReports.Application/Commands/CancelSettlementReportCommand.cs
source/settlement-report/SettlementReports.Application/Handlers/CancelSettlementReportJobHandler.cs
source/settlement-report/SettlementReports.Application/Handlers/ICancelSettlementReportJobHandler.cs
source/settlement-report/SettlementReports.Application/Handlers/ListSettlementReportJobsHandler.cs
source/settlement-report/SettlementReports.Application/SettlementReports_v2/SettlementReport.cs
source/settlement-report/SettlementReports.Infrastructure/Helpers/DatabricksJobsHelper.cs
source/settlement-report/SettlementReports.Interfaces/SettlementReports_v2/Models/SettlementReportStatus.cs
source/settlement-report/SettlementReports.UnitTests/Handlers/CancelSettlementReportJobHandlerTests.cs
source/settlement-report/SettlementReports.WebAPI/Controllers/SettlementReportsController.cs
source/settlement-report/SettlementReports.WebAPI/Extensions/DependencyInjection/SettlementReportModuleExtensions.cs

API to Cancel Settlement Report Jobs

---

source/settlement-report/Orchestration.SettlementReports.IntegrationTests/Fixtures/OrchestrationSettlementReportsAppFixture.cs
source/settlement-report/Orchestration.SettlementReports/host.json

https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/2515

Change storage account for duration function.

---

source/settlement-report/Orchestration.SettlementReports.IntegrationTests/Fixtures/OrchestrationSettlementReportsAppFixture.cs
source/settlement-report/Orchestration.SettlementReports/host.json

Reverts Energinet-DataHub/geh-settlement-report#60

Revert "Change storage account for duration function."

---

.github/workflows/detect-changes.yml

https://github.com/tj-actions/changed-files/issues/2463#issuecomment-2727015784

Update tj-actions/changed-files to v46.0.1

---

source/geh_settlement_report/pyproject.toml
source/geh_settlement_report/src/geh_settlement_report/entry_points/job_args/settlement_report_args.py
source/geh_settlement_report/tests/entry_points/test_settlement_report_output_path.py
source/geh_settlement_report/tests/integration_test/test_azure_monitor.py
source/geh_settlement_report/uv.lock

refac: Use GridAreaCodes type

---

source/geh_settlement_report/pyproject.toml
source/geh_settlement_report/src/geh_settlement_report/entry_points/entry_point.py
source/geh_settlement_report/tests/conftest.py
source/geh_settlement_report/uv.lock

chore: bump opentelemetry

---

source/geh_settlement_report/README.md

Update the README to reflect the correct folder name for the settlement report code.

Trigger deployment for geh_settlement_report

---

source/geh_settlement_report/README.md

Improve clarity in the README by refining the language for better understanding of the folder's purpose and functionality.

Update README for geh_settlement_report clarity

---

source/geh_settlement_report/README.md

Trigger deployment

---

.github/workflows/ci-orchestrator.yml
source/geh_settlement_report/pyproject.toml

Change the package version in the project configuration and update the CI workflow name for clarity.

Update package version to 1.0.0 and CI workflow name

---

source/settlement-report/SettlementReports.Infrastructure/Helpers/DatabricksJobsHelper.cs

Mark jobs with library installation errors as failed

---

source/geh_settlement_report/pyproject.toml
source/geh_settlement_report/src/geh_settlement_report/entry_points/entry_point.py
source/geh_settlement_report/src/geh_settlement_report/infrastructure/paths.py

feat: Added no-op job for settlement reports

---

source/settlement-report/Reports.SubsystemTests/Features/MeasurementsReport/MeasurementsReportScenario.cs
source/settlement-report/Reports.SubsystemTests/Features/MeasurementsReport/States/MeasurementstReportScenarioState.cs
source/settlement-report/SettlementReports.Interfaces/SettlementReports_v2/Models/MeasurementsReport/MeasurementsReportRequestDto.cs
source/settlement-report/SettlementReports.Interfaces/SettlementReports_v2/Models/MeasurementsReport/MeasurementsReportRequestFilterDto.cs
source/settlement-report/SettlementReports.Interfaces/SettlementReports_v2/Models/MeasurementsReport/RequestedMeasurementsReportDto.cs
source/settlement-report/SettlementReports.Interfaces/SettlementReports_v2/Models/RequestedSettlementReportDto.cs
source/settlement-report/SettlementReports.Interfaces/SettlementReports_v2/Models/SettlementReportRequestId.cs
source/settlement-report/SettlementReports.WebAPI/Controllers/MeasurementsReportsController.cs

feat: Refactor Measurements report DTOs and add new API endpoints

---

source/geh_settlement_report/src/geh_settlement_report/entry_points/entry_point.py
source/settlement-report/Reports.SubsystemTests/Features/SettlementReport/Fixtures/SettlementReportClient.cs
source/settlement-report/SettlementReports.Application/Handlers/RequestSettlementReportJobHandler.cs
source/settlement-report/SettlementReports.Application/MeasurementsReport/Handlers/RequestMeasurementsReportJobHandler.cs
source/settlement-report/SettlementReports.Function/Extensions/DependencyInjection/SettlementReportModuleExtensions.cs
source/settlement-report/SettlementReports.Infrastructure/SettlementReports_v2/SettlementReportJobsFileBlobStorage.cs
source/settlement-report/SettlementReports.UnitTests/Handlers/RequestSettlementReportJobHandlerTests.cs
source/settlement-report/SettlementReports.WebAPI/Controllers/MeasurementsReportsController.cs
source/settlement-report/SettlementReports.WebAPI/Extensions/DependencyInjection/SettlementReportModuleExtensions.cs

fix: Fix broken subsystem tests

---

source/geh_settlement_report/tests/test_factories/total_monthly_amounts_factory.py

refac: added typing to eliminate red line

---

source/geh_settlement_report/pyproject.toml

chore: bump geh_common

---

.github/CODEOWNERS

chore: Mandalorian is the new sheriff in town

---

.github/actions/dotnet-tests-prepare-outputs/action.yml
.github/workflows/ci-dotnet.yml
global.json
source/settlement-report/Common.Infrastructure/Common.Infrastructure.csproj
source/settlement-report/Directory.Build.props
source/settlement-report/Reports.SubsystemTests/Features/SettlementReport/Fixtures/ISettlementReportClient.cs
source/settlement-report/Reports.SubsystemTests/Reports.SubsystemTests.csproj
source/settlement-report/SettlementReports.Application/SettlementReports.Application.csproj
source/settlement-report/SettlementReports.Function/Extensions/DependencyInjection/SettlementReportModuleExtensions.cs
source/settlement-report/SettlementReports.Function/Program.cs
source/settlement-report/SettlementReports.Function/SettlementReports.Function.csproj
source/settlement-report/SettlementReports.Infrastructure/Experimental/DatabricksContextBase.cs
source/settlement-report/SettlementReports.Infrastructure/Extensions/DependencyInjection/CalculationResultsExtensions.cs
source/settlement-report/SettlementReports.Infrastructure/SettlementReports.Infrastructure.csproj
source/settlement-report/SettlementReports.IntegrationTests/SettlementReports.IntegrationTests.csproj
source/settlement-report/SettlementReports.Interfaces/SettlementReports.Interfaces.csproj
source/settlement-report/SettlementReports.UnitTests/SettlementReports.UnitTests.csproj
source/settlement-report/SettlementReports.WebAPI/SettlementReports.WebAPI.csproj
source/settlement-report/Test.Core/Test.Core.csproj

Tested on dev_003 [here](https://github.com/Energinet-DataHub/dh3-environments/actions/runs/15297191654).
https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/833

chore: Update to .NET 9

---

source/settlement-report/SettlementReports.Infrastructure/Persistence/MeasurementsReport/MeasurementsReportRepository.cs

feat: Add GetByJobRunIdAsync functionallity 

---

docs/Reports.Client/ReleaseNotes/ReleaseNotes.md
source/settlement-report/Reports.Abstractions/Reports.Abstractions.csproj
source/settlement-report/Reports.Client/MeasurementsReportClient.cs
source/settlement-report/Reports.Client/Reports.Client.csproj
source/settlement-report/Reports.Client/SettlementReportClient.cs

refac: Make client implementation public

---

source/geh_settlement_report/src/geh_settlement_report/measurements_reports/domain/calculation.py
source/geh_settlement_report/src/geh_settlement_report/measurements_reports/domain/output_mapper.py

refac: Move measurments report mapping to seperate file
